### ISSUE TITLE
 unexpected 'version' (T_STRING)

### ISSUE THREAD

**Issue by SlyDave** [alexpgates/nova-horizon-link#2]
Getting the following when using this plugin:
```
Symfony\Component\Debug\Exception\FatalErrorException
Method Illuminate\View\View::__toString() must not throw an exception, caught Facade\Ignition\Exceptions\ViewException: syntax error, unexpected 'version' (T_STRING) (View: /var/app/current/vendor/alexpgates/horizon-link/resources/views/navigation.blade.php)
```

![image](https://user-images.githubusercontent.com/1842611/75458510-d05ca680-5975-11ea-9d9a-861b25ef1920.png)

**Comment by alexpgates** [comment]
@SlyDave Any luck after clearing your view cache? `php artisan view:clear`

**Comment by SlyDave** [comment]
Sadly not, was my first port of call. It's working on my local machine but not when pushed to my AWS EB instance... and I'm stumped as to why. It seems to choke on the svg tag's attributes for some bizarre reason.

**Comment by alexpgates** [comment]
Do you have the PHP `short_open_tag` option set to ON on your AWS instance? You can check `phpinfo()`. Just spitballing here, but I can see how `<?xml` would confuse PHP if `short_open_tag` is enabled.

Frankly, I'm not even sure we need that xml stuff with the SVG anyway. I don't know enough about SVGs to know for sure why it'd be necessary.

**Comment by alexpgates** [comment]
@SlyDave I yanked the xml tag out and pushed another release after reading this: https://stackoverflow.com/questions/27413470/do-i-need-to-keep-the-xml-header-in-an-svg-file-when-embedding-it-in-the-web-pag

Any better?

**Comment by SlyDave** [comment]
![image](https://user-images.githubusercontent.com/1842611/75494852-138a3a00-59b5-11ea-9826-8464f1692e09.png)
Perfect, fixed 👍 

Thanks for your extremely fast turn around on that!

Now to work out wtf AWS EB defaults to having short tags enabled...
